version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mpays_dev
      MYSQL_USER: mpays_dev_admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
  wordpress:
    image: wordpress:6.4.3 # https://hub.docker.com/_/wordpress/
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - '.:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mpays_dev_admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mpays_dev
      WORDPRESS_TABLE_PREFIX: wp_
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 500M
    ports:
      - "8080:80"
    links:
      - db:db
